server:
  port: 8031
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
  instance:
    prefer-ip-address: true
turbine:
  appConfig: service-order
  clusterNameExpression: "'default'"