server:
  port: 7001 #服务端口
spring:
  application:
    name: rabbitmq-producer #指定服务名
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: xiaoxin-default   #指定消息发送的目的地  发送到名为itcast-default的交换机上
        myoutput:
          destination: xiaoxin-custom-default   #指定消息发送的目的地  发送到名为itcast-default的交换机上
          producer:
            partition-key-expression: payload
            partition-count: 2
      binders:
        defaultRabbit:
          type: rabbit
