server:
  port: 8081
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/    #server的请求方式
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1  # 采样比
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener: # 这里配置了重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  application:
    name: service-order
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 990219
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true

#配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
  instance:
    prefer-ip-address: true #使用IP地址注册


#logging:
#  level:
#    com.xin.order.feign.ProductFeignClient: debug
#    root: debug

#修改ribbon的负载均衡策略
#service-product:
#  ribbon:
#    ConnectTimeout: 250 #Ribbon的连接超时时间
#    ReadTimeout: 1000 #Ribbon的数据读取时间
#    OkToRetryOnAllOperations: true  #是否对所有操作都进行重试
#    MaxAutoRetriesNextServer: 1 #切换实例的重试次数
#    MaxAutoRetries: 1 #对当前实例的重试次数
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#配置feign日志的输出
feign:
#  client:
#    config:
#      service-product:
#        loggerlevel: FUll
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 5 #触发熔断的最小请求次数，默认20
        sleepWindowInMilliseconds: 10000 #熔断多少秒后去尝试请求 打开状态的时间
        errorThresholdPercentage: 50 #触发熔断的失败请求最小占比，默认50%

logging:
  level:
    root:
      org.springframework.web.servlet.DispatcherServlet: DEBUG
      org.springframework.cloud.sleuth: DEBUG