server:
  port: 7004 #服务端口
spring:
  application:
    name: rabbitmq-consumer #指定服务名
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      instanceCount: 2
      instanceIndex: 1
      bindings:
        input:  #内置获取通道
          destination: xiaoxin-default
        myinput: #自定义获取通道
          destination: xiaoxin-custom-default
          group: groupName    #消息组名称  同组内多个消费者只会有一个消费者消费
          consumer:
            partitioned: true
      binders:
        defaultRabbit:
          type: rabbit