server:
  port: 8070
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/    #server的请求方式
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1  # 采样比
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener: # 这里配置了重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  application:
    name: service-product
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 990219
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true

#配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/  #多个euerka用逗号隔开
  instance:
    prefer-ip-address: true #使用IP地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #向注册中心注册服务id
    lease-renewal-interval-in-seconds: 5 #发送心跳间隔
    lease-expiration-duration-in-seconds: 15 #续约到期时间

logging:
  level:
    root:
      org.springframework.web.servlet.DispatcherServlet: DEBUG
      org.springframework.cloud.sleuth: DEBUG
